package io.github.nhwalker.examples.api;

/**
 * Surfaces the api image's digest-pinned coordinate to application code.
 *
 * <p>{@code ApiImages} is generated by the container plugin (because the {@code api}
 * image opted in via {@code javaReference()}); its {@code API} constant holds the
 * image's {@code name:tag@sha256:...} reference, read from the image at build time.
 */
public final class ApiInfo {

    private ApiInfo() {
    }

    /** The digest-pinned coordinate of the api image. */
    public static final String IMAGE = ApiImages.API;
}
