package io.github.nhwalker.examples.reports;

/**
 * Surfaces the generic-artifact references to application code.
 *
 * <p>{@code ReportRefs} is generated by the artifacts plugin and carries both the
 * arbitrary {@code references} constants ({@code DEPLOY_ENV}, {@code BUNDLE_PATH}) and
 * the resource path of the bundled {@code report} artifact ({@code REPORT}).
 */
public final class ReportInfo {

    private ReportInfo() {
    }

    /** The deployment environment, declared as an arbitrary reference. */
    public static final String DEPLOY_ENV = ReportRefs.DEPLOY_ENV;

    /** The classpath resource path of the bundled report artifact. */
    public static final String REPORT_RESOURCE = ReportRefs.REPORT;
}
