package io.github.nhwalker.container.gradle.tasks;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.TreeMap;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

/**
 * Generates a Java interface ({@code <ProjectName>Images}) exposing each declared
 * image's full docker identifier as a {@code public static final String} constant.
 *
 * <p>The constant name is the image name converted to upper-case with underscores
 * (for example {@code webServer} or {@code web-server} becomes {@code WEB_SERVER}),
 * and its value is the image's primary tag (the first tag when several are declared).
 *
 * <p>The generated source lives under the task's {@link #getOutputDirectory() output
 * directory}, which the plugin adds to the {@code main} Java source set so it is
 * compiled with the project. The file is (re)generated whenever an image is built.
 */
public abstract class GenerateImageReferencesTask extends DefaultTask {

    /** The project name; the generated interface is named {@code <ProjectName>Images}. */
    @Input
    public abstract Property<String> getProjectName();

    /** The package the interface is generated into. When unset/blank, the default package is used. */
    @Input
    @Optional
    public abstract Property<String> getPackageName();

    /** Maps each image name to its full docker identifier (its primary/first tag). */
    @Input
    public abstract MapProperty<String, String> getImages();

    /** The root directory the {@code .java} file is written into (a source root). */
    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @TaskAction
    public void generate() {
        String typeName = interfaceName(getProjectName().get());
        String packageName = sanitizePackage(getPackageName().getOrElse(""));
        // Sort for a deterministic, diff-friendly output independent of declaration order.
        Map<String, String> images = new TreeMap<>(getImages().get());

        StringBuilder source = new StringBuilder();
        if (!packageName.isEmpty()) {
            source.append("package ").append(packageName).append(";\n\n");
        }
        source.append("// Generated by the io.github.nhwalker.container plugin. Do not edit.\n");
        source.append("public interface ").append(typeName).append(" {\n");
        for (Map.Entry<String, String> entry : images.entrySet()) {
            source.append("    public static final String ")
                    .append(constantName(entry.getKey()))
                    .append(" = \"").append(escape(entry.getValue())).append("\";\n");
        }
        source.append("}\n");

        Path root = getOutputDirectory().get().getAsFile().toPath();
        Path target = packageName.isEmpty()
                ? root.resolve(typeName + ".java")
                : root.resolve(packageName.replace('.', '/')).resolve(typeName + ".java");
        try {
            Files.createDirectories(target.getParent());
            Files.writeString(target, source.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write generated image references " + target, e);
        }
    }

    /** The interface name for a project: its name in PascalCase with an {@code Images} suffix. */
    public static String interfaceName(String projectName) {
        StringBuilder sb = new StringBuilder();
        boolean upperNext = true;
        for (int i = 0; i < projectName.length(); i++) {
            char c = projectName.charAt(i);
            if (Character.isLetterOrDigit(c)) {
                sb.append(upperNext ? Character.toUpperCase(c) : c);
                upperNext = false;
            } else {
                upperNext = true;
            }
        }
        if (sb.length() == 0 || Character.isDigit(sb.charAt(0))) {
            sb.insert(0, '_');
        }
        return sb.append("Images").toString();
    }

    /** Converts an image name to an UPPER_SNAKE_CASE Java constant identifier. */
    public static String constantName(String imageName) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < imageName.length(); i++) {
            char c = imageName.charAt(i);
            if (Character.isLetterOrDigit(c)) {
                boolean boundary = Character.isUpperCase(c) && i > 0
                        && (Character.isLowerCase(imageName.charAt(i - 1))
                                || Character.isDigit(imageName.charAt(i - 1)));
                if (boundary && sb.length() > 0 && sb.charAt(sb.length() - 1) != '_') {
                    sb.append('_');
                }
                sb.append(Character.toUpperCase(c));
            } else if (sb.length() > 0 && sb.charAt(sb.length() - 1) != '_') {
                sb.append('_');
            }
        }
        while (sb.length() > 0 && sb.charAt(sb.length() - 1) == '_') {
            sb.setLength(sb.length() - 1);
        }
        if (sb.length() == 0 || Character.isDigit(sb.charAt(0))) {
            sb.insert(0, '_');
        }
        return sb.toString();
    }

    /** Keeps only valid Java identifier segments, dropping anything that can't form a package. */
    private static String sanitizePackage(String value) {
        if (value == null || value.isBlank()) {
            return "";
        }
        StringBuilder result = new StringBuilder();
        for (String segment : value.strip().split("\\.")) {
            StringBuilder clean = new StringBuilder();
            for (int i = 0; i < segment.length(); i++) {
                char c = segment.charAt(i);
                if (Character.isJavaIdentifierPart(c)) {
                    if (clean.length() == 0 && !Character.isJavaIdentifierStart(c)) {
                        clean.append('_');
                    }
                    clean.append(c);
                }
            }
            if (clean.length() > 0) {
                if (result.length() > 0) {
                    result.append('.');
                }
                result.append(clean);
            }
        }
        return result.toString();
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
